version: '3'

services:
  postgresql:
    image: postgres:16
    container_name: java_db
    ports:
      - "5437:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=java_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgresql: { }